
- name: Install Nginx
  apt: state=latest name=nginx

- name: Build Nginx whole configuration file - nginx.conf
  template: src=../templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  #notify: restart nginx

- name: Build Nginx site configuration file - conf.d/default.conf
  template: src=../templates/conf.d/default.conf.j2 dest=/etc/nginx/conf.d/default.conf

#- name: Build Nginx site configuration file - conf.d/api.conf
#  template: src=../templates/conf.d/api.conf.j2 dest=/etc/nginx/conf.d/api.conf
  #notify: restart nginx

- name: Awake Nginx
  service: name=nginx enabled=yes state=restarted

