
- name: Install uWSGI via Pip
  command: /opt/local/bin/pip2.7 install uwsgi

- name: Symbolic Link uWSGI
  command: ln -s -f /opt/local/bin/uwsgi /usr/bin/uwsgi

- name: Prepare pid warehouse /var/run/uwsgi
  command: mkdir -f /var/run/uwsgi && chmod 0777 /var/run/uwsgi

- name: Prepare log warehouse /var/log/uwsgi
  command: mkdir -f /var/log/uwsgi && chmod 0777 /var/log/uwsgi


