- name: Install iptables
  yum: name=iptables state=installed

- name: Change mode 777 iptables
  command: chmod 0777 /etc/sysconfig/iptables

- name: Copy template for iptables
  command: cp /vagrant/roles/iptables/files/iptables /etc/sysconfig/iptables

- name: Change mode 600 iptables
  command: chmod 0600 /etc/sysconfig/iptables

- name: Awake Network
  service: state=restarted name=network

- name: Awake iptables
  service: state=restarted name=iptables

