
- name: Set timezone variables
  copy: content='Asia/Tokyo'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

